name: GrAde
description: GrAde for mobile

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  keyboard_visibility: any
  provider: any
  cloud_firestore: any
  firebase_auth: any
  firebase_messaging: any
  firebase_analytics: any
  cupertino_icons: any
  google_sign_in: any
  url_launcher: any
  firebase_remote_config: any

flutter:
  uses-material-design: true
