name: GrAde
description: GrAde for mobile

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.2.4"
  cloud_firestore: "0.7.3"
  firebase_auth: "0.5.12"
  firebase_messaging: "1.0.3"
  firebase_analytics: "1.0.1"
  firebase_remote_config: "0.0.2"
  cupertino_icons: "0.1.2"
  google_sign_in: "3.0.4"
  url_launcher: "3.0.3"

flutter:
  uses-material-design: true
