name: GrAde
description: GrAde for mobile

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: "0.7.3"
  firebase_auth: "0.5.12"
  firebase_messaging: "1.0.3"
  cupertino_icons: "0.1.0"
  google_sign_in: "3.0.4"

flutter:
  uses-material-design: true
